### ISSUE TITLE
Upgrade to embedded-linux 1.0

### ISSUE THREAD

**Issue by clintfred** [eldruin/tmp1x2-rs#2]
Would it be possible to upgrade tmp1x2-rs to embedded-linux 1.0? 

Do you have any feeling for how hard this will be? We might be able to help, if it's fairly straightforward.

**Comment by eldruin** [comment]
I have now done the update to `embedded-hal` 1.0 and published [version 1.0.0](https://github.com/eldruin/tmp1x2-rs/releases/tag/v1.0.0) :tada:

**Comment by clintfred** [comment]
Thanks so much for the quick response and release. I really appreciate how you maintain your crates!

**Comment by eldruin** [comment]
Thanks for the kind words.
